# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'My Mind' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for My Mind
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '12.1'
  use_frameworks!

  pod 'SwiftForms'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'


  target 'My MindTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'My MindUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
